= Meta-Notes

What makes for a good set of book notes? What is the best process to follow? 

I have no idea, but right now here are my best guesses:

* Try to read uninterrupted, don't put that book down
    ** Too much reading flow can be lost from the context switch between reading and note taking
    ** This is esp. true for me since I am a slow reader -- plus most of my reading happens when note taking would be inconvenient
* Jot down some well organized notes a few chapters at a time
    ** This acts as a nice review of the materials, forces you to work through them again
    ** Don't wait until the end of the book, that is too much to bite off
* Keep the notes short
    ** Don't worry about subsections are headings, just summarize the high-level take-aways
    ** I think my _Code Complete_ notes are far too detailed (probably why I quit that book) and my _Brain Rules for Baby_ notes are just about right
* Write the notes on the computer, in asciidoc
    ** I _love_ my notebook and fountain pens, however they are not amenable to the book note taking task
    ** First, physical notes need to be written sequentially -- the oft necessary book jumping doesn't work
    ** Second, computer notes can be started, stopped, and edited at any time -- great increasing the probability of note-taking
    ** Finally, computerized notes are searchable, more legible, and more easily shareable than paper notes
    ** _All that being said_, there is definitely still a place for my daily work journaling. There the requirements and workflow are much different: the goal is more to talk through a problem and extract thoughts than to write down information which will be referenced in the future

**Organizing Principles**:
* Increase probability of actual note-taking :white_check_mark:
* Allow backfilling and editing when needed :white_check_mark:
* Increase usability of note product :white_check_mark: