= Brain Rules for Baby

Subtitle: How to Raise a Smart and Happy Child from Zero to Five

Author: John Medina

== Introduction

* The purpose of parenting is brain development
* Brain science is complicated, be careful not to read too much into studies


== Pregnancy

* In-utero brain techniques like listening to Mozart are mostly bunk
* The development of the brain is incredible, thousand of cells a second
* At the beginning, some cells make the amniotic sac, others make the baby (!!)
* Morning sickness _could_ lead to smarter babies because of the hormones involved
* Babies can smell and taste, and develop preferences based on those inputs, from inside the womb
* Stress hormones from the mother can affect the developing baby

== Relationship

* Initial baby-rearing is incredibly trying and stressful (even more than we expect)
* When fighting happens between parents, it is important for parents to reconcile in front of the kids
* Four biggest reasons for fighting:
    ** *Sleep Loss*: loss of sleep causes stress which is hard to cope with. Additionally the load is uneven between husband and wife.
    ** *Social Isolation*: spending so much time in a one-sided relationship can be draining. Try to make time for social interactions even when being a new parent (ultimately relationships are the only thing that make people happy!)
    ** *Unequal Workload*: There can be resentment if the two parents are not sharing the work evenly. This is difficult when the mother has several unique responsibilities early on.
    ** *Depression*: This is less common but new parents are susceptible to depression which can drive relationships further apart.
* However, the news is not all bad: most happy people are married
* The key to staying together is practicing extreme empathy
* Most of us are unaware of how little information we are sharing about our internal state (or how little other people share about theirs)
* We need to realize that behind the actions and words of others are many explanatory thoughts and emotions
* On the flip side, if we want others to understand where we are coming from we need to share more information than at first seems necessary
* Finally, preparing for the new child by considering these factors before the new baby comes home is a recipe of success

== Smart Baby: Seeds

* A lot of interesting science on brain development and growth (nothing much applicable tho)
* Up to 50% of intelligence is genetic
* Addresses the fact that IQ is not perfect but it does correlate with many other measures of success/intelligence
* Ingredients of intelligence include: self-control, creativity, communication skills, and a desire to explore

== Smart Baby: Soil

* The brain's job is not learning -- it is surviving. Therefore completely leaving the baby be will not create a learning environment
* Four key "brain boosters"
    ** *Breastfeeding*: though I think these studies have causation/correlation issues, there is some research indicating that breastfeeding is beneficial for brain growth and long term outcomes
    ** *Talk to the Baby*: babies need lots of varied communication, even from a very young age. Communication is a core human activity, triggering those parts of the brain early is goo
        *** Also the words need to come from a human being, not a machine. Little Einsteins DVDs did very little for the babies
    ** *Quality Playtime*: certain types of open-ended yet planned play are beneficial. Studies showed that forms of constrained pretend time or "mature dramatic play" improved all sorts of cognitive indicators like memory, IQ, self control, etc.
    ** *Praise Effort, Not IQ*: the idea here is that praising effort instills a growth mindset which is essential for learning (and has large, measurable effects). Praising a kid for doing something smart does not prepare them for the next time where they need to learning something first (leaving the child frustrated and without a game-plan). Praising the effort encourages the _process_ of knowledge acquisition, reinforcing behaviors which, when repeated, lead to success.
* TV before the age of two is generally discouraged, after that things are less clear
* However there is no better learning environment than interacting with real life people in person
* Jury is also out on video games, however the mind loves exercise so static activities should always be moderated
* Excessive texting may also delay development -- again, the face to face interactions are what kids need the most
* Finally, really high expectations may inhibit intellectual growth. High stress situations like this discourage exploration and risk taking which are essential to high performance

== Happy Baby: Seeds

* Even in happiness genetics can play a large role
* Some babies are highly reactive and are challenging to sooth from the get-go (and this continues throughout their life)
* Long term studies into happiness indicate that the single most important factor influencing happiness is deep, meaningful relationships with other people
* Regulating emotions is an essential skill for developing relationships (as well as succeeding in many other areas of life)
* Emotions are like tags or post-it notes on stimuli which help the brain identify, filter, and prioritize

== Happy Baby: Soil

* How we respond to our children's actions _profoundly_ matters to his future happiness
* Parents and children can develop strong bonds or attachments early on through parent attentiveness. This attachment is very import for proper brain development
* However full attachment takes years -- don't sweat lacking attachment early on
* Researchers have identified "terrific kids" which exhibit the following qualities:
    ** have better emotional regulation, calming themselves more quickly
    ** have the highest academic achievement
    ** show great empathetic responses
    ** show greater loyalty to parents with higher compliance with parental wishes (this coming from respect rather than fear)
    ** have fewer incidents of pediatric depression and anxiety
    ** have the fewest infectious diseases
    ** are less prone to acts of violence
    ** have deeper, richer friendships, and more of them
* Obviously this is a laundry list of desireable traits -- how do we make that happen?
* Studies have addressed this question and have apparently found common characteristics across controls and populations
* Main takeaway: emotions are central to the parenting style
* Here are the six components to good parenting, all focused around the emotional health of your child:
    ** *1: A demanding but warm parenting style*
        *** One way think about parenting is across two dimensions: demanding-ness (generally how strict you are) and responsiveness (generally how well you care for your child's emotional well-being)
        *** Low demanding, low responsive parents are essentially neglectful because they do not discipline their child nor care for their well-being
        *** Low demanding, high responsive parents are indulgent because they want their children to be happy but do not discipline
        *** High demanding, low responsive parents are Authoritarian, imposing rules for their children out of need to control, rather than love
        *** High demanding, high responsive parents are Authoritative, they set boundaries for their children but do so out of the love they have
        *** Clearly high demanding, high responsive is the best approach because rules authority is established while the child's emotional well-being is tended to
    ** *2: Comfort with your own emotions*
        *** Being aware of your own emotions and knowing how to handle them is essential 
IMPORTANT: Kids are constantly watching, modeling healthy behaviors in general is a key responsibility of every parent
        *** Additionally, it is important to recognize that there is no such things as bad emotions, only bad reactions to those emotions
        *** Families which teach that emotions are hard to control but you do control your reaction are more likely to have happier kids
    ** *3: Tracking emotions*
        *** Parents should pay very close attention to the emotional state of their children
        *** First, this allows you to better empathize with how they are feeling
        *** Second, it allows you to predict how they might behave, enabling all sorts of countermeasures for sticky situations
        *** One caveat though: paying too much attention and acting on those predictions can be stiffling. Part of paying close attention is noticing when the child needs a break to act their own without parental interventions
    ** *4: Communicating emotions*
        *** Beyond being comfortable and accepting about emotions, it is important to track those emotions over time
        *** For your emotions, make a point to share how you feel in certain situations so the child knows that the parent is also feeling many emotions
        *** For your child's emotions, try to "tag" what your child is feeling by asking them if they sad, mad, happy, etc
        *** Neurologically, this tagging can actually help two areas of the brain talk to each other, improving your child's ability to regulate
        *** Behaviorally, the child will begin to pattern match and recognize the feeling they are having. With this recognition, the child can be more aware of their response to the emotion, take certain steps which will help them cope with the emotion, or share the emotion they are feeling with those around them,
