= Chapter 2: Types and Functions

* Types are a method of telling the computer exactly what form a variable should take
* Types impose a constraint on the set of all possible programs, allowing us to eliminate entire classes of programs before running them (much like how grammar and spelling help constrain English Sentences)
* Category Theory is all about composing arrows and types tell us what kinds of arrows can be composed

== What are types?

* Types can be thought of as sets. `x :: Integer` means that the variable `x` belongs to the set of integers
** In Haskell, `Integer` is an infinite set w/ arbitrary precision while `Int` is a finite set like you see in C++
* Types as sets, while not perfect, is a good analogy because it introduces our first category: *Set*
* In this category, the objects are sets and the morphisms are functions
* Sets are a useful category because we can look inside and develop intuitions. However our goal will be to abstract away from the specifics of Set and consider its properties in terms of Categories
* We can't directly apply mathematical rigor to Haskell, however, because Haskell needs to actually run code in order to get an answer
* By running code we run into issues of non-termination. To handle this we will augment our type sets with a "bottom", denoted `_|_`.
* Any kind of non-termination, including errors, can be represented by a bottom
* This introduction, however, causes all sorts of headaches which make Haskell types not quite equivalent to Set. Thus we call the category of Haskell types and functions _Hask_.
* Fundamentally Hask is not Set, but for our purposes we can treat them the same

== 2.4: Why do we need a mathematical model?
* Many languages have a formal grammar which is well defined.
* However the semantics of the language  is hard to define.
* Tools for describing the semantics of a language exist but they are often only applicable to restricted academic languages
* One tool, _operational semantics_, describes the function of a language via a idealized interpreter.
* Functionally this means that the operation of code is only analyzed by simulating how it is run
* The problem with this is that programmers are not very good trying to run code in their head
* An alternative is _denotational semantics_ which assigns mathematical meaning to each programming construct
* In doing so we can make semantic guarantees by "proving" things about the mathematical structures underlying our code
* Haskell is quite amenable to this type of analysis
* Consider the factorial function given below:

[code,haskell]
----
fact n = product [1...n]
----

* The above function can easy be modeled using denotational semantics -- but this is a cheat!! (it is just math anyway)
* For other tasks the parallel is not as clear
** What is the mathematical model for sending a packet over the network? 
** For reading files?
* These questions were hard to answer until *Eugenio Moggi* discovered a Category Theory solution via *Monads*
* This connection allows Mathematical Proofs of correctness for code (many of which underpin the Haskell standard library)

== 2.5: Pure and Dirty Functions
* Functions which always produce the same output and do not do anything else (ie have side effects) are called *Pure Functions*

QUESTION: Are all Haskell functions pure?

* Monads allow effects to be modeled using pure functions

== 2.6: Examples of Types
* C++ has no empty-set type, Haskell has `Void`
* No function can have a `Void` input type because this set has no values, meaning that the function could never be called
* The singleton type is represented in C++ by `void`. Functions which take or returning `void` can be thought of as taking or returning the same dummy value
* In Haskell this type (and its value) are the empty parens: `()` (also referred to as Unit)
* In a sense, a function which maps Unit to a value is really just another way of representing that value (every value in a type has an associated Unit function)
* When a pure function returns Unit the we no that the function is a no-op
* Functions which have the same implementation for any type are called Parametrically Polymorphic
* C++ and Haskell have the same Type w/ two values: `bool`/`Bool`
* Pure functions which return `Bool` must choose between the two possible values. Such functions are called predicates
